######################################################################
# Automatically generated by qmake (2.01a) Mo. Aug 31 18:05:49 2015
######################################################################

TEMPLATE = subdirs

# Directories


HEADERS += \
	c_grammar.h \
	c_nodes.h \
	parsers.h \
	c_tokens.h

SOURCES += \
	main.cpp \
	parsers.cpp

OTHER_FILES += Makefile

