######################################################################
# Automatically generated by qmake (2.01a) Mo. Aug 31 18:05:49 2015
######################################################################

TEMPLATE = subdirs

# Directories


HEADERS += token.h

SOURCES += token.cpp \
	main.cpp

OTHER_FILES += Makefile

